### ISSUE TITLE
34411A Package don't work

### ISSUE THREAD

**Issue by gkaur2** [pklaus/agilent_34411a#1]
Whenever i tried to run " pip install https://github.com/pklaus/agilent_34411A/archive/master.zip" in mine Raspberry pi 2 LXTerminal, below error comes.

error: file '/tmp/pip-nDIORg-build/scripts/agilent_34411A_cli' does not exist

Please help me to fix this issue or else please suggest any alternative to read value from Agilent DMM.I am very new to programming. I need python script to run on raspberry which can read the Voltage value through ethernet interface. Thanks in advance.

**Comment by pklaus** [comment]
Thanks for letting me know. I think I fixed the problem in 19b54f7. Can you please try again?

**Comment by gkaur2** [comment]
Hi Philipp Klaus

Thanks a lot for your quick response.
The previous issue is solved now  but I faced other issue while using it.

NameError : global name ‘ConnectionRefusedError’ is not defined.

For your reference I am writing whole procedure:

```
sudo pip install https://github.com/pklaus/agilent_34411A/archive/master.zip
Python _init_.py
Python cli.py
```

It shows

cli.py : error : too few arguments

```
Python cli.py 169.254.251.117 --apply-function PT100 --output-format '{:.03f} °C' --interval 0.9 --avg-samples 1
```

It shows `NameError : global name ‘ConnectionRefusedError’ is not defined.`

I have run ifconfig on LXTerminal of raspberry pi board, and got 169.254.251.117.

Please help me to fix this issue.

If you have any document or something which explains step by step procedure, please share it with me, I will follow that to make it working.
My basic need is to read the voltage value from 34411A DMM.

Thanks a lot.

**Comment by gkaur2** [comment]
Hi Philip

I tried to replace the IP address with IP address of 34411A DMM , and got the below error:

NameError: global name ‘Agilent34411A’ is not defined.

Thanks in advance.
Please let me know what should I do.

**Comment by pklaus** [comment]
Yes, there was a bug in the code. Just install the update using:

```
sudo pip install --upgrade https://github.com/pklaus/agilent_34411A/archive/master.zip
```

But why do you run `Python cli.py`? Just run `agilent_34411a_cli` as stated in the README and you should be ready to go. The `pip install` command has set up everything for you. You don't need to download and unpack the code other than installing it with the `pip` command.

And yes, the IP address **of the multimeter** has to be specified. And you probably don't need to apply any additional calculation function on the data for now. So your call would be:

```
agilent_34411a_cli 169.254.251.117 --interval 2 --avg-samples 1
```

**Comment by gkaur2** [comment]
I tried in same manner but  got below error

Bash: agilent_34411a_cli : command not found

**Comment by pklaus** [comment]
So what was the output of the `sudo pip install --upgrade https://github.com/pklaus/agilent_34411A/archive/master.zip` command?

Or to pin it down a bit more precisely:

```
sudo pip install \
--upgrade \
--verbose \
https://github.com/pklaus/agilent_34411A/archive/master.zip | grep _cli
```

**Comment by gkaur2** [comment]
The output was :
Upgradation done, setup.py installed

Now I tried in following way:
I have done that bug fix change in _init_.py manually  and then run as below
Python cli.py 169.254.4.10 --interval 2 --avg-samples 1
It works.
Thanks a lot Philipp for your help.

**Comment by pklaus** [comment]
I'm glad that you are finally getting the readings from your voltmeter.

I found out why your efforts running the CLI interface directly didn't work: There was a lowercase / uppercase confusion and the way it was stated in the README was incorrect.

Now I'm sticking to the following rules:
- The package is called `agilent_34411a` (also this Github repository was renamed to all-lowercase)
- The CLI is called `agilent_34411a_cli` (as stated already in the README already before, when it was in fact agilent_34411**A**_cli)
- The class is called `Agilent_34411A`, (no change here).

I also put a bit more information in the README.

All the best!

**Comment by gkaur2** [comment]
Hi Philipp

Do we have any python script or package which can export the voltage values read from 34411A DMM to excel sheet ?
If yes, please send me link for same as unable to find on github site.

Thanks for your support.
Gagan
